# Voidlinux container builders (buildahs)
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc:

This repository contains https://github.com/containers/buildah[`buildah`] scripts for building
OCI compliant or Docker formatted voidlinux containers.

## Usage

### Configuration

All configuration can be done through environment variables

`author`:: The full 'MAINTAINER' value for image and container metadata
`created_by`:: This becomes the prefix all images use, i.e. with 'created_by=foo', the images would be `foo/alpine-voidbuilder`, `foo/void-voidbuilder`, and `foo/voidlinux`
`REPOSITORY`:: This is the url of the voidlinux repository to use (default: https://alpha.de.repo.voidlinux.org)
`ARCH`:: The architecture to build (default: x86_64). See build.voidlinux.org for available arches.
`BASEPKG`:: The base package (or packages) to install in the final voidlinux container. (default: base-minimal)
`tag`:: The tag to give this image (Default: `${ARCH}-latest`

Export these variables before running the build scripts.

Alternately, you can use the -a ARCH, -t TAG, -b BASEPKG options to the scripts to set those three variables.

IMPORTANT: You must have fuse-overlayfs working in order for the buildah scripts to work properly (from within the unshare session, if using one)

### Building

#### Build everything (First-Time build)

The `./buildah.sh` script will build 3 images, similar to the voidlinux https://hub.docker.com/r/voidlinux/voidlinux/dockerfile[dockerfile].

This script only needs to be run when you want to rebuild the underlying base images (alpine-voidbuilder and void-voidbuilder).
They can also be run individually (see below).

TIP: The build scripts use `buildah mount`, which may require you to run them in a `buildah unshare` session

#### Build individual images

You can build just the layer you want to refresh with the individual scripts

`./alpine-builder.sh`:: Builds the `${created_by}/alpine-voidbuilder:${tag}` image
`./void-builder.sh`:: Builds the `${created_by}/void-voidbuilder:${tag}` image
`./voidlinux-final.sh`:: Builds the `${created_by}/voidlinux:${tag}` image

## Images

Three images are built by the `./buildah.sh` script.

`${created_by}/alpine-voidbuilder`:: A bare alpine image with void bootstrapped at /target
`${created_by}/void-voidbuilder`:: A voidlinux image with $BASEPKG installed at /target
`${created_by}/voidlinux`:: The final configured and stripped voidlinux image, suitable for running containers, or using as a base for other containers

### Publishing the images
These images are available in the buildah local registry, as viewed with `buildah images`.

To export to a local docker registry, use `buildah push "${created_by}/voidlinux/voidlinux:${tag}" docker-daemon:<image_name>:<tag>`

See https://github.com/containers/buildah/blob/master/docs/buildah-push.md[The buildah-push documentation] for how to push to various
other registries.

### Running the images

These images are available to podman immediately, and can be run with `podman run -it --rm ${created_by}/voidlinux:${tag}`
 (will run the voidlinux container's default cmd: `/bin/sh`).

To run with docker, first publish to a docker registery, then use `docker run -it --rm <image_name>:<tag>`, where `<image_name>` and `<tag>`
are the names you published to the docker registry.

## CI / CD

These 3 images are built nightly using https://gitlab.com/bougyman/voidlinux-containers/-/pipelines[gitlab pipelines],
and available from https://gitlab.com/bougyman/voidlinux-containers/container_registry/eyJuYW1lIjoiYm91Z3ltYW4vdm9pZGxpbnV4LWNvbnRhaW5lcnMvdm9pZGxpbnV4IiwidGFnc19wYXRoIjoiL2JvdWd5bWFuL3ZvaWRsaW51eC1jb250YWluZXJzL3JlZ2lzdHJ5L3JlcG9zaXRvcnkvMTIxNDczOC90YWdzP2Zvcm1hdD1qc29uIiwiaWQiOjEyMTQ3Mzh9[This Gitlab Registry]
