FROM registry.gitlab.com/bougyman/voidlinux-containers/voidlinux:tmux-tiny
LABEL maintainer="bougyman <bougyman@hey.com>" \
      description="Void Linux image with 'tmux' with glibc (no glibc-locales) and busybox instead of coreutils. All libs stripped" \
      origin="registry.gitlab.com/bougyman/voidlinux-containers/voidlinux:tmux-tiny"
ENTRYPOINT []
CMD /usr/bin/tmux
